### ISSUE TITLE
柱状图网格线怎样设置为虚线呢

### ISSUE THREAD

**Issue by ningstudy** [DataV-Team/Charts#3]
配置文档没找到这个选项

**Comment by jiaming743** [comment]
```javascript
xAxis: {
  splitLine: {
    style: {
      lineDash: [3,3]
     }
  }
}
```

Charts的demo中有网格线虚线实例 不管是柱图还是折线图 坐标轴配置是相同的[demo](http://charts.jiaminghi.com/example/bar.html#%E6%9F%B1%E7%BA%BF%E6%B7%B7%E7%94%A8)

Charts的底层渲染插件是**CRender**，样式可以查看其**Style**类[CRender-LineDash](http://crender.jiaminghi.com/guide/style.html#linejoin)
