### ISSUE TITLE
渲染后canvas中的文字很模糊

### ISSUE THREAD

**Issue by meguoe** [DataV-Team/Charts#8]
渲染后canvas中的文字很模糊，这是什么原因，有参数控制？

**Comment by jiaming743** [comment]
在不同环境下 pixel-ratio 是不同的，即1视觉像素实际上用多少个物理像素去渲染是不同的，高分辨率屏幕下还没有添加相应的处理，所以会导致模糊，下个大版本会添加支持，近期会更新。

**Comment by meguoe** [comment]
好的，谢谢！

**Comment by meguoe** [comment]
> 在不同环境下 pixel-ratio 是不同的，即1视觉像素实际上用多少个物理像素去渲染是不同的，高分辨率屏幕下还没有添加相应的处理，所以会导致模糊，下个大版本会添加支持，近期会更新。

好的，谢谢！

**Comment by meguoe** [comment]
> 在不同环境下 pixel-ratio 是不同的，即1视觉像素实际上用多少个物理像素去渲染是不同的，高分辨率屏幕下还没有添加相应的处理，所以会导致模糊，下个大版本会添加支持，近期会更新。

请问这个最新版本有支持吗？

**Comment by lyutian** [comment]
`"@jiaminghi/data-view": "^2.10.0"`还是会模糊。看了release，很久没发新版了。
可能[echarts](https://echarts.apache.org/zh/index.html) 太好用了。这个项目不准备更新了。。
